name: Setup FluentCI With Args

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-fluentci:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@v2
      - name: Setup FluentCI
        uses: ./
        with:
          wasm: true
          plugin: base
          args: |
            hello Tsiry Sandratraina
            hello again
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
