name: Setup FluentCI With Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-fluentci:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@v2
      - name: Setup FluentCI
        uses: ./
        with:
          wasm: true
          engine-version: 0.2.6
          args: base_pipeline hello Tsiry Sandratraina
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
